language: node_js

node_js:
    - "4.1"
    - "4.0"
    - "0.12"
    - "0.11"
    - "0.10"
    - "0.8"
    - "0.6"
    - "iojs"

services:
    - redis

before_script:
    - npm install -g mocha
    - npm install -g typescript
    - npm run build
